# Generated by Django 3.1.1 on 2021-05-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_message_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='creator',
        ),
        migrations.AlterField(
            model_name='lot',
            name='image',
            field=models.ImageField(blank=True, upload_to='lots'),
        ),
    ]
